FROM ubuntu:22.04

RUN apt-get update -y \
    && apt-get -y --no-install-recommends install python3.10 python3-pip python3.10-venv git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global user.name hoge
RUN git config --global user.email hoge@hoge.com

WORKDIR /work