version: "3.9"

services:

  mysql:
    image: mysql:8.0.32
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
      - TZ=Asia/Tokyo

  python:
    build:
      context: .
      dockerfile: ./dockerfile_ubuntu_python_dev
    image: ubuntu_python3.10
    container_name: python
    restart: always
    volumes:
      - ../workspaces:/home/vscode/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
